title:            Thiago Rodrigues
description:      Full Stack Developer
url:              https://thiago.github.io
signoff:          Thiago Rodrigues
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-41416516-4

links:
  - name:         About
    url:          /
  - name:         Blog
    url:          /blog
  - name:         GitHub
    url:          http://github.com/thiago
    external:     true
  - name:         Linkedin
    url:          https://linkedin.com/in/thiagorsouz
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
